export const DEFAULT_GIFTS = [
    { name: "Conjunto de talheres (garfos, facas, colheres)", category: "Cozinha", imageUrl: "https://cf.shopee.com.br/file/br-11134207-7r98o-lp6iza7h4vidfd", buyLink: "https://s.shopee.com.br/70DgPozxmT", priceEstimate: 99.9 },
    { name: "Conjunto de pratos (rasos, fundos, sobremesa)", category: "Cozinha", imageUrl: "https://cf.shopee.com.br/file/br-11134207-7r98o-ma9wbmp4u0e117", buyLink: "https://s.shopee.com.br/8zyknbKisy", priceEstimate: 124.9 },
    { name: "Copos", category: "Cozinha", imageUrl: "https://cf.shopee.com.br/file/br-11134207-7r98o-mb5nnw9a7c0f0f", buyLink: "https://s.shopee.com.br/1BFtTJq2zf", priceEstimate: 42.9 },
    { name: "Panela de pressão", category: "Cozinha", imageUrl: "https://cf.shopee.com.br/file/sg-11134201-7rdwb-m0x78cp0sfyca0", buyLink: "https://s.shopee.com.br/6KxzczRw1Z", priceEstimate: 139.12 },
    { name: "Assadeiras", category: "Cozinha", imageUrl: "", buyLink: "https://s.shopee.com.br/9KbbCZAZEY", priceEstimate: null },
    { name: "Tábua de cortar", category: "Cozinha", imageUrl: "https://cf.shopee.com.br/file/sg-11134201-7rbm5-m5d121s72yd0c5", buyLink: "https://s.shopee.com.br/W0CgTixWn", priceEstimate: 89.97 },
    { name: "Conjunto de utensílios", category: "Cozinha", imageUrl: "https://cf.shopee.com.br/file/sg-11134201-7rdya-m024n5dghn0a54", buyLink: "https://s.shopee.com.br/9fERbNUqiR", priceEstimate: 86.39 },
    { name: "Ralador/Descascador", category: "Cozinha", imageUrl: "https://cf.shopee.com.br/file/sg-11134201-7rdw4-lyfko349gab0ac", buyLink: "https://s.shopee.com.br/8APdofzkK5", priceEstimate: 115.61 },
    { name: "Potes herméticos", category: "Cozinha", imageUrl: "https://cf.shopee.com.br/file/sg-11134201-7rast-ma39uigua8pd55", buyLink: "https://s.shopee.com.br/7V9x1WICN9", priceEstimate: 89.9 },
    { name: "Potes mantimentos", category: "Cozinha", imageUrl: "https://cf.shopee.com.br/file/sg-11134201-7rdxy-lxis6bqt6xfue1", buyLink: "https://s.shopee.com.br/5q1j2VRndx", priceEstimate: 119.9 },
    { name: "Porta tempero", category: "Cozinha", imageUrl: "https://cf.shopee.com.br/file/br-11134207-7r98o-m6xepi2ftels18", buyLink: "https://s.shopee.com.br/1gCA5BdVgp", priceEstimate: 52.5 },
    { name: "Cafeteira elétrica", category: "Eletrodomésticos", imageUrl: "https://cf.shopee.com.br/file/sg-11134201-7rffx-m9yiew8r4trda5", buyLink: "https://s.shopee.com.br/3VdoGHqb4x", priceEstimate: 149.9 },
    { name: "Torradeira", category: "Eletrodomésticos", imageUrl: "https://cf.shopee.com.br/file/sg-11134201-7rfi1-m9yigvqshztbc4", buyLink: "https://s.shopee.com.br/13w5tcNbY", priceEstimate: 159.9 },
    { name: "Liquidificador", category: "Eletrodomésticos", imageUrl: "https://cf.shopee.com.br/file/br-11134207-7r98o-mc83lzgst4gw71", buyLink: "https://s.shopee.com.br/6KxzdaD3gf", priceEstimate: 99.99 },
    { name: "Chaleira elétrica", category: "Eletrodomésticos", imageUrl: "https://cf.shopee.com.br/file/br-11134207-81z1k-mfo2ou0hkao01c", buyLink: "https://s.shopee.com.br/10wTHpA9OV", priceEstimate: 122.9 },
    { name: "Airfryer", category: "Eletrodomésticos", imageUrl: "https://cf.shopee.com.br/file/br-11134207-81ztc-mivj61ur5z4198", buyLink: "https://s.shopee.com.br/3fxESmP7HO", priceEstimate: null },
    { name: "Vassoura, pá e rodo", category: "Lavanderia", imageUrl: "https://cf.shopee.com.br/file/sg-11134201-7repu-m8xms5gkp3px67", buyLink: "https://s.shopee.com.br/3B0xs1N37C", priceEstimate: 61.9 },
    { name: "Balde", category: "Lavanderia", imageUrl: "https://cf.shopee.com.br/file/sg-11134201-7reo7-m8evgw0duobb5b", buyLink: "https://s.shopee.com.br/20p0Tv4DAR", priceEstimate: 62.9 },
    { name: "Esfregões", category: "Lavanderia", imageUrl: "https://cf.shopee.com.br/file/br-11134207-81z1k-mh0gpooee611d9", buyLink: "https://s.shopee.com.br/AAAiD39xaN", priceEstimate: 69.99 },
    { name: "Cestos de roupa", category: "Lavanderia", imageUrl: "https://cf.shopee.com.br/file/br-11134207-81z1k-mgokugbz3g9128", buyLink: "https://s.shopee.com.br/AUnYbjp0K3", priceEstimate: 54.29 },
    { name: "Roupas de limpeza (esponjas, escovas, flanelas)", category: "Lavanderia", imageUrl: "https://cf.shopee.com.br/file/br-11134207-7r98o-m48w7dr9yf9d8c", buyLink: "https://s.shopee.com.br/8KjFtindnG", priceEstimate: 15.49 },
    { name: "Toalhas de banho e rosto", category: "Banheiro", imageUrl: "https://cf.shopee.com.br/file/br-11134207-7r98o-m50gz5vd1aya23", buyLink: "https://s.shopee.com.br/1VsvlJEHWw", priceEstimate: 69.9 },
    { name: "Tapete antiderrapante", category: "Banheiro", imageUrl: "https://cf.shopee.com.br/file/sg-11134201-7rdxv-md6gn8s9a3nkce", buyLink: "https://s.shopee.com.br/8pfWZVVGmC", priceEstimate: 33.9 },
    { name: "Porta-sabonete/dispensers", category: "Banheiro", imageUrl: "https://cf.shopee.com.br/file/sg-11134201-7rbk4-m5vz4m8260ifcb", buyLink: "https://s.shopee.com.br/5fiUnkbEy", priceEstimate: null },
    { name: "Cesta organizadora", category: "Banheiro", imageUrl: "https://cf.shopee.com.br/file/br-11134207-81z1k-mggb77065p1j3e", buyLink: "https://s.shopee.com.br/1LZVdr3Fh4", priceEstimate: 50.55 },
    { name: "Lixeira para banheiro", category: "Banheiro", imageUrl: "https://cf.shopee.com.br/file/br-11134207-7r98o-mdapzb7cvo6qb0", buyLink: "https://s.shopee.com.br/8pfWZihgbP", priceEstimate: 69.9 },
    { name: "Lençol e fronha", category: "Quarto", imageUrl: "https://cf.shopee.com.br/file/br-11134207-7r98o-m6s7hmorl4cn9d", buyLink: "https://s.shopee.com.br/40aGoxNRzS", priceEstimate: 57 },
    { name: "Cobre-leito", category: "Quarto", imageUrl: "https://cf.shopee.com.br/file/br-11134207-81z1k-micx08rups030d", buyLink: "https://s.shopee.com.br/BNYG6FntA", priceEstimate: 117.64 },
    { name: "Travesseiros", category: "Quarto", imageUrl: "https://cf.shopee.com.br/file/sg-11134201-7rdwj-mc3ykysuflimb9", buyLink: "https://s.shopee.com.br/1qVmFDPqVJ", priceEstimate: 74.87 },
    { name: "Cabides", category: "Quarto", imageUrl: "https://cf.shopee.com.br/file/br-11134207-81z1k-mfcs3uwyls783e", buyLink: "https://s.shopee.com.br/9KbnB29Tkr", priceEstimate: 49.9 },
    { name: "Edredom", category: "Quarto", imageUrl: "https://cf.shopee.com.br/file/e7f9fde9067d4c36e9c7c8202ff90f5b", buyLink: "https://s.shopee.com.br/6KyBbb1Q1O", priceEstimate: 83.99 },
    { name: "Almofadas", category: "Sala", imageUrl: "https://cf.shopee.com.br/file/br-11134207-7r98o-ma8srfzstx892f", buyLink: "https://s.shopee.com.br/6VHfbFfw9f", priceEstimate: 41.79 },
    { name: "Manta para sofá", category: "Sala", imageUrl: "https://cf.shopee.com.br/file/sg-11134201-8258m-mgfbsqcsxtl520", buyLink: "https://s.shopee.com.br/4fq1PudRkR", priceEstimate: 47.49 },
    { name: "TV", category: "Sala", imageUrl: "https://cf.shopee.com.br/file/br-11134207-7r98o-lukqws4dn82cf9", buyLink: "https://s.shopee.com.br/1BG9Fb9wSI", priceEstimate: 877.99 },
    { name: "Caixas organizadoras", category: "Organização", imageUrl: "https://cf.shopee.com.br/file/sg-11134201-822y3-mi5g1zd9c35udf", buyLink: "https://s.shopee.com.br/AAAxyD0Shg", priceEstimate: 22.9 },
    { name: "Organizadores de gaveta", category: "Organização", imageUrl: "https://cf.shopee.com.br/file/br-11134207-7qukw-ljmp8btohrii2a", buyLink: "https://s.shopee.com.br/4VWbDq3Dw5", priceEstimate: 29.9 },
    { name: "Estante", category: "Organização", imageUrl: "https://cf.shopee.com.br/file/sg-11134201-7ren6-m8dkpbtglpjl06", buyLink: "https://s.shopee.com.br/6puW0CRiV4", priceEstimate: 489.9 },
    { name: "Suportes para sapatos/armário", category: "Organização", imageUrl: "https://cf.shopee.com.br/file/sg-11134201-7rdyd-lzqcdl1n0gv6e1", buyLink: "https://s.shopee.com.br/2VlWqGzD9B", priceEstimate: 49.99 },
    { name: "Quadros/decor", category: "Decoração", imageUrl: "https://cf.shopee.com.br/file/br-11134207-7r98o-maczkveepq4v1b", buyLink: "https://s.shopee.com.br/2B8gRkOeTc", priceEstimate: 240 },
    { name: "Luminárias ou abajur", category: "Decoração", imageUrl: "https://cf.shopee.com.br/file/sg-11134201-821gb-mh807gw3nqbx6a", buyLink: "https://s.shopee.com.br/2qONF2TMlk", priceEstimate: 59.99 },
    { name: "Tapetes", category: "Decoração", imageUrl: "https://cf.shopee.com.br/file/br-11134207-7r98o-m969t86ug8xl5e", buyLink: "https://s.shopee.com.br/1qVq3E62I4", priceEstimate: 41.31 },
    { name: "Extensões e filtros de tomada", category: "Utilidades", imageUrl: "https://cf.shopee.com.br/file/sg-11134201-824gy-mfed14o5tgy7d5", buyLink: "https://s.shopee.com.br/8V2jzWjhsk", priceEstimate: 42.98 },
    { name: "Câmera de segurança", category: "Utilidades", imageUrl: "", buyLink: "https://s.shopee.com.br/1Vszelpzu1", priceEstimate: null },
    { name: "Jogo de jogos de tabuleiro", category: "Lazer", imageUrl: "https://cf.shopee.com.br/file/br-11134207-81z1k-mfn8wv32chz854", buyLink: "https://s.shopee.com.br/AKUOB3m5qc", priceEstimate: 174.99 },
    { name: "Balde de gelo", category: "Lazer", imageUrl: "https://cf.shopee.com.br/file/sg-11134201-7rfh6-m3wg9oezmv6oe8", buyLink: "https://s.shopee.com.br/9AIQmx77Su", priceEstimate: 33.27 },
];
